-- CREATE TABLE games(
--     gid uniqueidentifier, 
--     name varchar(255), 
--     rid int, 
--     system varchar(255), 
--     description text,
--     edition varchar(255)

-- CREATE TABLE library(
--     gid int, 
--     bid uniqueidentifier,
--     brid int,
--     title varchar(255)
--     type varchar(255),
--     description text,
--     path varchar,
--     image text,
--     publisher (varchar)
--     )